swagger: "2.0"
info:
    description: "API de Dados Abertos Relacionados da UFFS"
    version: "1.0.0"
    title: "Transparência UFFS"
schemes:
- "https"
paths:
  /dataset:
      get:
          tags:
          - "Dados Abertos"
          summary: "Obter Nomes dos Datasets"
          description: "Obtém a lista de nomes dos datasets compartilhados pelo Portal de Dados Abertos da UFFS"
          operationId: "obterNomesDatasetsDisponiveis"
          consumes:
          - "application/json"
          produces:
          - "application/json"
          responses:
              "200":
                  description: Consulta realizada com sucesso
                  schema:
                      type: "array"
                      items:
                        type: string
                        example: "matriz_graduacao"
  /dataset/{datasetName}/resource:
      get:
          tags:
          - "Dados Abertos"
          summary: "Obter Conteúdo do Dataset"
          description: "Obtém os dados do recurso do dataset informado e relacionados"
          operationId: "obterConteudoDataset"
          consumes:
          - "application/json"
          produces:
          - "application/json"
          parameters:
          - name: "datasetName"
            in: "path"
            required: true
            type: "string"
            description: "Nome do dataset"
            default: "projetos_cultura"
          - name: "filtros"
            in: "header"
            required: false
            type: "string"
            description: "Filtro com nome do campo e valor em formato de objeto Json"
            default: "{\"_id\":\"335276c4-bbd6-490a-bb4c-e49d7c1d9540\"}"
          - name: "relacionamentos"
            in: "header"
            required: false
            type: "string"
            description: "Em formato CSV, específica colunas que serão consideradas como passíveis de formar relacionamento entre datasets"
            default: "id_turma,cod_ccr,cod_uffs"
          responses:
              "200":
                  description: Consulta realizada com sucesso
                  schema:
                      $ref: "#/definitions/ObterConteudoDatasetResponse"

definitions:
  ObterConteudoDatasetResponse:
    type: "object"
    properties:
        help:
            type: string
            example: "https://dados.uffs.edu.br/api/3/action/help_show?name=datastore_search"
        success:
            type: boolean
            example: true
        result:
            $ref: "#/definitions/ResourceResponseResultResponse"

  ResourceResponseResultResponse:
    type: "object"
    properties:
        include_total:
            type: boolean
            example: true
        resource_id:
            type: string
            example: "f54123ff-40b6-40bd-9fce-b8a4a7f8b219"
        fields:
            type: "array"
            items:
                $ref: "#/definitions/ResourceResponseResultFieldResponse"
        records_format:
            type: string
            example: "lists"
        _links:
            $ref: "#/definitions/LinksResponse"
        filters:
            $ref: "#/definitions/Filters"
        total:
            type: integer
            example: 1
        recordsWithRelationships:
            type: "array"
            items:
                $ref: "#/definitions/ResourceComRelacionamentoResponse"

  ResourceResponseResultFieldResponse:
    type: "object"
    properties:
        type:
            type: string
        id:
            type: string

  LinksResponse:
    type: "object"
    properties:
        start:
            type: string
            example: "/api/3/action/datastore_search?records_format=lists&filters=%7B%22_id%22%3A%22286bd0bf-1a6e-4b32-b2a3-cf186d3f7b20%22%7D&resource_id=f54123ff-40b6-40bd-9fce-b8a4a7f8b219"
        next:
            type: string
            example: "/api/3/action/datastore_search?offset=100&records_format=lists&filters=%7B%22_id%22%3A%22286bd0bf-1a6e-4b32-b2a3-cf186d3f7b20%22%7D&resource_id=f54123ff-40b6-40bd-9fce-b8a4a7f8b219"

  Filters:
    type: "object"
    properties:
        _id:
            type: string
            example: "286bd0bf-1a6e-4b32-b2a3-cf186d3f7b20"

  ResourceComRelacionamentoResponse:
    type: "object"
    properties:
        camposOriginais:
            $ref: "#/definitions/CamposOriginaisResponse"
        camposRelacionados:
            type: "array"
            items:
                $ref: "#/definitions/CamposRelacionadosResponse"

  CamposOriginaisResponse:
    type: "object"
    properties:
        nome_campo_x:
            type: string
            example: "valor_campo_x"

  CamposRelacionadosResponse:
    type: "object"
    properties:
        nomeDataset:
            type: string
            example: "projetos_cultura"
        nomeCampoRelacionado:
            type: string
            example: "coordenador"
        conteudoRecurso:
            type: string
            example: "retorno da consulta"